### ISSUE TITLE
[BUG] Install command removes fields from super.json

### ISSUE THREAD

**Issue by martinalbert** [superfaceai/cli#100]
## Description 
`install` command removes retryPolicy, priority or providerFailover fields from super.json

## Expected Behaviour
CLI shouldn't remove existing fields. After `install` is executed, super.json should be modified only on places where it should be modified, if new profile is installed, no other profile should be affected and if already existing profile is installed, his settings in super.json should be preserved.

## Current Behaviour
Currently `install` modifies whole super.json document and removes mentioned fields. This behaviour is not occurring only when using `sf install` without specifying profile or force flag.

## Possible Solution
Update [mutate module](https://github.com/superfaceai/one-sdk-js/blob/main/src/internal/superjson/mutate.ts) for super.json to work with new superjson schema.

## Steps to Reproduce
1. create Superface project
2. install profile
3. set up retry policy
4. install another profile

**Comment by Jakub-Vacek** [comment]
This issue was actually problem in SDK - it is fixed now. So in CLI we just need to use not beta version of SDK (when it will be released).

**Comment by martinalbert** [comment]
So I decided to test it with new sdk and `retryPolicy` is still getting removed.

**cli version:** 
```
@superfaceai/cli/0.0.19 darwin-x64 node-v15.4.0 (with @superfaceai/one-sdk@0.0.29-beta.4+91971d72, @superfaceai/parser@0.0.17)
```

**initial super.json:**
```
{
  "profiles": {
    "starwars/character-information": {
      "version": "1.0.1",
      "defaults": {
        "RetrieveCharacterInformation": {
          "providerFailover": true
        }
      },
      "providers": {
        "swapi": {
          "retryPolicy": "circuit-breaker"
        }
      }
    }
  },
  "providers": {
    "swapi": {
      "security": []
    }
  }
}
```

_testing configure command_
```
sf configure mock -p starwars/character-information
```
- `mock` provider was added to providers, but `retryPolicy` from `swapi` was removed
- `priority` was added, but only contains specified `mock` provider (might be better to scan for other providers and add them as well)

_testing install command_
```
sf install starwars/character-information -f
```
- `retryPolicy` from `swapi` provider is removed after install
